name: CI for IoT Dashboard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup .NET SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./src/IoTDashboard/IoTDashboard.csproj

      # Build the project
      - name: Build the project
        run: dotnet build --configuration Release ./src/IoTDashboard/IoTDashboard.csproj

      # Test the project
      - name: Run tests
        run: dotnet test ./src/IoTDashboard/IoTDashboard.csproj

      # Build Docker image
      - name: Build Docker image
        run: docker build -t iot-dashboard ./src/IoTDashboard